env:
  commonjs: true
  es2020: true
  node: true
  mocha: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  no-unused-expressions: 0
  chai-friendly/no-unused-expressions: 2
plugins:
  - chai-friendly
