name: CI
on: [push]

jobs:
  build:
    name: CI
    runs-on: [self-hosted, linux, docker]
    container:
      image: docker://hashicorp/terraform:0.12.28
    env:
      TF_CLI_CONFIG_FILE: "terraformrc"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
    
      - name: Terraform auth
        env:
          TF_CLI_CONFIG_FILE_CONTENT: ${{ secrets.TF_CLI_CONFIG_FILE_CONTENT }} 
        run: |
          tfConfigFilePath=$TF_CLI_CONFIG_FILE
          echo $TF_CLI_CONFIG_FILE_CONTENT > $tfConfigFilePath

      - name: Terraform init
        env:
          BACKEND_DEV_TFVARS_JSON: ${{ secrets.BACKEND_DEV_TFVARS_JSON }}
        run: |
          backendFilePath=backend.tfvars.json
          echo $BACKEND_DEV_TFVARS_JSON > $backendFilePath
          terraform init -backend-config=$backendFilePath

      - name: Terraform validate
        run: |
          terraform validate

      - name: Load Terraform vars
        env:
          GOOGLE_TFVARS_JSON: ${{ secrets.GOOGLE_DEV_TFVARS_JSON }}
          APP_GITHUB_TFVARS_JSON: ${{ secrets.APP_GITHUB_TFVARS_JSON }}
        run: |
          googleTfvarsJsonPath=google.auto.tfvars.json
          echo $GOOGLE_TFVARS_JSON > $googleTfvarsJsonPath

          githubTfvarsJsonPath=github.auto.tfvars.json
          echo $APP_GITHUB_TFVARS_JSON > $githubTfvarsJsonPath

      - name: Install Terraform dependencies
        run: |
          apk add npm
          apk add nodejs
          npm install -g yarn
          cd modules/runners/scripts && yarn

      - name: Terraform plan
        run: |
          terraform plan -lock=false
      